version: 2.1
jobs:
  test:
    parameters:
      python-version:
        type: string
      with:
        type: string
      postgres-version:
        type: string
    docker:
      - image: cimg/<< parameters.python-version >>
      - image: cimg/<< parameters.postgres-version >>
        environment:
          POSTGRES_DB: 'auditmatic'
          POSTGRES_USER: 'audit'
          POSTGRES_PASSWORD: 'matic'
    steps:
      - checkout
      - run: pip install --user pipenv
      - run: PIPENV_QUIET=True pipenv lock --dev -r > requirements.txt
      - run: pip install -r requirements.txt
      - run: ./qa.sh
      - run: python manage.py behave


workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              python-version: ["python:3.8.13", "python:3.9.13", "python:3.10.4"]
              with: ["with"]
              postgres-version: ["postgres:14.2", "postgres:13.6", "postgres:11.15"]