version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - run: pip install --user pipenv
      - run: pipenv install
      - run: pipenv install --dev --pre
      - run: pipenv run ./qa.sh
