version: 2.1
jobs:
  test:
    parameters:
      python-version:
        type: string
      postgres-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
      - image: cimg/postgres:<< parameters.postgres-version >>
        environment:
          POSTGRES_DB: 'auditmatic'
          POSTGRES_USER: 'audit'
          POSTGRES_PASSWORD: 'matic'
    steps:
      - checkout
      - run: pip install --user pipenv
      - run: PIPENV_QUIET=True pipenv lock --dev -r > requirements.txt
      - run: pip install -r requirements.txt
      - run: ./qa.sh
      - run: python manage.py behave


workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              python-version: ["3.8.13", "3.9.13", "3.10.4"]
              postgres-version: ["14.2", "13.6", "11.15"]
          name: Python << parameters.python-version >> with PostgreSQL << paramenters.postgres-version >>