version: 2.1
jobs:
  test:
    parameters:
      python-image:
        type: string
      postgres-image:
        type: string
    docker:
      - image: << parameters.python-image >>
      - image: << parameters.postgres-image >>
        environment:
          POSTGRES_DB: 'auditmatic'
          POSTGRES_USER: 'audit'
          POSTGRES_PASSWORD: 'matic'
    steps:
      - checkout
      - run: pip install --user pipenv
      - run: PIPENV_DONT_USE_PYENV=True PIPENV_QUIET=True pipenv install --system --skip-lock
      - run: PIPENV_DONT_USE_PYENV=True PIPENV_QUIET=True pipenv install --dev --pre --system --skip-lock
      - run: PIPENV_DONT_USE_PYENV=True pipenv run ./qa.sh
      - run: PIPENV_DONT_USE_PYENV=True pipenv run python manage.py behave

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              python-image: ["cimg/python:3.7.13", "cimg/python:3.8.13", "cimg/python:3.9.13", "cimg/python:3.10.4"]
              postgres-image: ["cimg/postgres:14.2", "cimg/postgres:13.6", "cimg/postgres:11.15", "cimg/postgres:10.20", "cimg/postgres:9.6.24"]