version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run: sudo apt-get update -y && sudo apt-get install pipenv -y
      - run: pipenv install
      - run: ./qa.sh
