version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.7
      - image: cimg/postgres:14.2.0
        environment:
          POSTGRES_DB: 'auditmatic'
          POSTGRES_USER: 'audit'
          POSTGRES_PASSWORD: 'matic'
    steps:
      - checkout
      - run: pip install --user pipenv
      - run: pipenv install
      - run: pipenv install --dev --pre
      - run: pipenv run ./qa.sh
      - run: pipenv run python manage.py behave
